// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a sample product",
                            ImageUrl = "https://via.placeholder.com/150",
                            IsActive = true,
                            Name = "Sample Product 1",
                            Price = 9.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is another sample product",
                            ImageUrl = "https://via.placeholder.com/150",
                            IsActive = true,
                            Name = "Sample Product 2",
                            Price = 19.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is yet another sample product",
                            ImageUrl = "https://via.placeholder.com/150",
                            IsActive = true,
                            Name = "Sample Product 3",
                            Price = 29.99m,
                            Stock = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a new sample product",
                            ImageUrl = "https://via.placeholder.com/150",
                            IsActive = true,
                            Name = "Sample Product 4",
                            Price = 39.99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is the fifth sample product",
                            ImageUrl = "https://via.placeholder.com/150",
                            IsActive = true,
                            Name = "Sample Product 5",
                            Price = 49.99m,
                            Stock = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Latest Apple iPhone 13",
                            ImageUrl = "https://via.placeholder.com/150",
                            IsActive = true,
                            Name = "iPhone 13",
                            Price = 999.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Apple MacBook Pro with M1 chip",
                            ImageUrl = "https://via.placeholder.com/150",
                            IsActive = true,
                            Name = "MacBook Pro",
                            Price = 1999.99m,
                            Stock = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
